apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    source-file: podinfo-GitRepository-resource.yaml
  name: podinfo
  namespace: podinfo
spec:
  interval: 3m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
